### PR TITLE
Update entities

### PR DESCRIPTION
**Pull request by Chebotarev**
@ataber Another one for you, I also wanted to try bumping the version number. Do you know if that creates a new release automatically?

### CODE REVIEW

**Comment by ataber** [comment]
Looks good to me! It doesn't create a new release, I'll do that though

**Comment by Chebotarev** [comment]
Thanks!

**Comment by Chebotarev** [comment]
Hey @ataber, would you mind creating a new release? I'm having some issues pulling in the latest changes without it, thanks!

**Comment by ataber** [comment]
Okay I made a new release. Hopefully it should work now! Let me know if there's still issues

**Pull request merged**
